data_dir: custom_dataset
log_dir: ../reproducibility/custom_dataset\model
config: null
task: synthetic
wandb_entity: null
group_name: null
wandb_mode: online
job_type: dev-train
online: false
dataset: custom_dataset
n_samples: 10000
train_bs: 32
val_bs: 8
transform: null
split_fracs:
- 0.8
- 0.1
- 0.1
num_workers: 1
in_dim: 30
out_dim: 30
timestep_emb_dim: 64
h_dim: 64
n_layers: 2
activation: silu
dropout_p: 0.1
run_name: jhsadfbfb
n_epochs: 10
use_grad_noise: false
drift_weight: 1.0
reg_weight: 1.0
reg_weight_T: 1.0
reg_weight_t: 1.0
diffusivity_schedule: constant
max_diffusivity: 0.7
use_drift_in_doobs: true
optim_name: adamw
lr: 0.001
weight_decay: 0.001
grad_clip_value: 10.0
scheduler: plateau
scheduler_mode: min
scheduler_patience: 10
ema_decay_rate: 0.999
log_every: 1000
eval_every: 10000
inference_every: 0
inference_steps: 100
inference_metric: val_rmsd
inference_goal: min
early_stop_metric: val_loss
early_stop_goal: min
